
export const menuItems = [
    {
        key:'/',
        icon:'home',
        title:'首页'
    },
    {
        key:' /appstore',
        icon:'appstore',
        title:'商品',
        children:[
            {
                key:'/category',
                icon:'bars',
                title:'分类管理'
            },
            {
                key:'/product',
                icon:'tool',
                title:'商品管理'
            }
        ]
    },
    {
        key:'/user',
        icon:'user',
        title:'用户管理'
    },
    {
        key:'/role',
        icon:'safety-certificate',
        title:'权限管理'
    },
    {
        key:'/areaChart',
        icon:'area-chart',
        title:'图形图表',
        children:[
            {
                key:'/barChart',
                icon:'bar-chart',
                title:'柱状图'
            },
            {
                key:'/lineChart',
                icon:'line-chart',
                title:'折线图'
            },
            {
                key:'/pieChart',
                icon:'pie-chart',
                title:'饼状图'
            }
        ]
    }
];